packages:
  - 'packages/*'
  - 'demo'

overrides:
  '@napi-rs/wasm-runtime': ^1.2.1
  '@bomb.sh/tab': ^0.0.22
  brace-expansion: ^5.0.9
  glob: ^13.0.6

allowBuilds:
  '@parcel/watcher': true
  esbuild: true

minimumReleaseAgeExclude:
  - '@napi-rs/wasm-runtime@1.2.1'
